export const british = {
  "--primary": "#2C4A3E",
  "--surface": "#F5F0EB",
  "--secondary": "#8B7355",
  "--text": "#1A1A1A",
  "--muted": "#9E9E9E",
  "--border": "#D4C9B8",
  "--accent": "#C17F3E",
  "--mm-radius-sm": "2px",
  "--mm-radius-md": "3px",
  "--mm-radius-lg": "4px",
  "--mm-font-family": "Georgia, serif",
  "--error": "#9B4444",
  "--error-bg": "#F5EDED",
} as const;
