// auto-generated by maid-melisa — do not edit directly
// edit templates/components/envelope.template.tsx instead
export { Envelope } from "../../templates/components/envelope.template"
export type { EnvelopeProps } from "../../templates/types/envelope.type"