// auto-generated by maid-melisa — do not edit directly
// edit templates/components/steeper.template.tsx instead
export { Steeper } from "../../templates/components/steeper.template"
export type { SteeperProps } from "../../templates/types/steeper.type"