// auto-generated by maid-melisa — do not edit directly
// edit templates/components/sugar-cube.template.tsx instead
export { SugarCube } from "../../templates/components/sugar-cube.template"
export type { SugarCubeProps } from "../../templates/types/sugar-cube.type"