// auto-generated by maid-melisa — do not edit directly
// edit templates/components/tea-tier.template.tsx instead
export { TeaTier } from "../../templates/components/tea-tier.template"
export type { TeaTierProps } from "../../templates/types/tea-tier.type"