// auto-generated by maid-melisa — do not edit directly
// edit templates/components/trolley.template.tsx instead
export { Trolley } from "../../templates/components/trolley.template"
export type { TrolleyProps } from "../../templates/types/trolley.type"