// templates/generators/builders/file.builder.ts

import { ComponentSchema } from "../types/schema.type";

export const buildFile = (schema: ComponentSchema): string => {
  const kebabName = schema.name
    .replace(/([a-z])([A-Z])/g, "$1-$2")
    .toLowerCase();

  return `// auto-generated by maid-melisa — do not edit directly
// edit templates/components/${kebabName}.template.tsx instead
export { ${schema.name} } from "../../templates/components/${kebabName}.template"
export type { ${schema.name}Props } from "../../templates/types/${kebabName}.type"`;
};
